TARGET = a_int_HW712_SM3_SM4_TOTAL_print_test


CFLAGS += -O3 -g
#根据SIMU宏选择串口波特率,0：FPGA上板；1：仿真
CFLAGS += -DSIMU=1

C_SRCS := $(wildcard ./*.c )
INCLUDES := -I. \
			-I./include 
#mychange			

OBJDIR = obj
COMMON_DIR = ../../bsp
GCC_DIR=../../../toolchains/loongson-gnu-toolchain-8.3-x86_64-loongarch32r-linux-gnusf-v2.0
PICOLIBC_DIR=../../../toolchains/picolibc
include ../../bsp/common.mk
